// <auto-generated />
using IssuesSystem.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IssuesSystem.DAL.Migrations
{
    [DbContext(typeof(IssuesContext))]
    [Migration("20230321161057_init1")]
    partial class init1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevoloperTicket", b =>
                {
                    b.Property<int>("devolopersId")
                        .HasColumnType("int");

                    b.Property<int>("ticketsId")
                        .HasColumnType("int");

                    b.HasKey("devolopersId", "ticketsId");

                    b.HasIndex("ticketsId");

                    b.ToTable("DevoloperTicket");
                });

            modelBuilder.Entity("IssuesSystem.DAL.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Automotive & Baby"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Beauty & Health"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Electronics"
                        });
                });

            modelBuilder.Entity("IssuesSystem.DAL.Models.Devoloper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Devolopers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 2,
                            Name = "Diabetes"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Name = "Hypertension"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Name = "Asthma"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Name = "Depression"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            Name = "Arthritis"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            Name = "Allergy"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            Name = "Flu"
                        });
                });

            modelBuilder.Entity("IssuesSystem.DAL.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            DepartmentId = 2,
                            Description = "Harum hic impedit dolore voluptate placeat.",
                            Severity = 1,
                            Title = "in"
                        },
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Description = "Rerum totam est quo possimus sunt sunt ad.",
                            Severity = 0,
                            Title = "id"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 3,
                            Description = "Id cumque explicabo beatae.",
                            Severity = 1,
                            Title = "dicta"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Description = "Consectetur beatae dolorem voluptates occaecati.",
                            Severity = 0,
                            Title = "eius"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Description = "Nulla est doloribus ut non aspernatur vero dolores.",
                            Severity = 2,
                            Title = "assumenda"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            Description = "Et praesentium est ipsum eligendi rerum itaque voluptate quia.",
                            Severity = 1,
                            Title = "ex"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            Description = "Optio non debitis ut molestiae dolorem ad.",
                            Severity = 2,
                            Title = "velit"
                        });
                });

            modelBuilder.Entity("DevoloperTicket", b =>
                {
                    b.HasOne("IssuesSystem.DAL.Models.Devoloper", null)
                        .WithMany()
                        .HasForeignKey("devolopersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuesSystem.DAL.Ticket", null)
                        .WithMany()
                        .HasForeignKey("ticketsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IssuesSystem.DAL.Models.Devoloper", b =>
                {
                    b.HasOne("IssuesSystem.DAL.Models.Department", "Department")
                        .WithMany("Devolopers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IssuesSystem.DAL.Ticket", b =>
                {
                    b.HasOne("IssuesSystem.DAL.Models.Department", "Department")
                        .WithMany("Tickets")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IssuesSystem.DAL.Models.Department", b =>
                {
                    b.Navigation("Devolopers");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
